baseURL = "https://www.applied-polisci.com/"
languageCode = "en-us"
title = "Applied Poli Sci"
theme = "ezhil"
paginate = 5

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

copyright = "© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-155314533-1"
# disqusShortname = 

[privacy]
  [privacy.disqus]
    disable = true

[params]
	subtitle = "where academic research meets current events"
	disableDisqusTypes = ["page", "posts"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/sophie_e_hill"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
