


Contentious consensus
How did the world know how to protest George Floyd's death?





*****************************

One Hundred Years of Silence

How did 8 minutes 46 seconds become the symbol of the George Floyd protests?

8 minutes 46 seconds. That was the length of time that prosecutors said police officer Derek Chauvin knelt on George Floyd's neck.

In fact, prosecutors later issued a correction -- it was actually 7 minutes 46 seconds -- after the Associated Press pointed out that the original timestamps 

https://apnews.com/d39cf4e1460fa14f0e339d85f21ad3c2

But the number had already become the symbol of the movement.

Protestors across the U.S. and, indeed, the world held moments of silence for the duration of 8 minutes 46 seconds.

There is an inherent theatricality to these silences. 

While congressional Democrats [knelt](https://www.pbs.org/newshour/nation/watch-congressional-democrats-hold-moment-of-silence-to-honor-george-floyd), protestors in [Pittsburgh](https://www.ellwoodcityledger.com/news/20200607/8-minutes-46-seconds-police-brutality-protests-reveal-uncomfortable-truths-prompt-local-action), [Sacramento](https://www.sacbee.com/news/local/article243321501.html), [Boston](https://www.nbcboston.com/news/local/george-floyd-protest-planned-for-boston-common-wednesday/2136307/) laid face down on the ground in a symbolic "die-in".

And these two performances were intertwined in a subversive reenactment when activists in Bristol knelt on the neck of the toppled statue of Edward Colston, a man who profited from the enslavement of tens of thousands of men, women, and children.

It may seem strange to puzzle over these performances. Holding moments of silence is a familiar practice, both as remembrance and as protest. And the symbol - 8 minutes and 46 seconds - communicated one of the most horrifying aspects of the incident. That is couldn't possibly be chalked up to a "split second reaction" or an adrenaline-fuelled mistake. 

But turning "8 minutes 46 seconds" into a silent protest only seems natural to us because it is part of a familiar *repertoire*.

This was the analogy that Charles Tilly famously used to understand why during times of protest -- which were necessarily, moments of upheaval and change -- participants seemed to confine themselves to familiar scripts [@tilly2008contentious, pp.11-12]

> On one side, people who make contentious claims in a given time and place draw on a very limited repertoire of performances. Most of the performances are sufficiently familiar that participants know more or less how to behave and what to expect. London’s skilled workers of the 1760s knew about assembling outside Mansion House and calling on the Lord Mayor, just as middle-class Londoners of the 1830s knew how to conduct a public meeting and how to send Parliament a petition. Those performances only change slowly and incrementally. But they do change continuously; even the public meetings of 1834 look somewhat different from the public meetings of 1768.

> On the other side, no two contentious performances mirror each other perfectly. Indeed, they would lose some of their effect if they operated like precision military drill. Participants improvise constantly in two different ways: figuring out how to shape the available routines to communicate the claims they are currently pursuing, and responding to other people’s reactions as they make the claims. They interact with other participants, onlookers, objects of claims, competitors, and authorities. In the process, they introduce minor innovations into established forms. Most of those innovations disappear as the event ends. But some stick. As a result, some performances disappear, others come into being, and most others modify incrementally.

Collective silences have been employed by the Black Lives Matter movement since its inception. One important innovation has been to connect the duration of the silence to a particular detail from the case of police brutality that sparked the protest. This is an astute tactic for ensuring that salient details of the case stay under media scrutiny.

In November 2014, Michael Brown's family asked for [4.5 minutes of silence](https://www.washingtonpost.com/politics/grand-jury-reaches-decision-in-case-of-ferguson-officer/2014/11/24/de48e7e4-71d7-11e4-893f-86bd390a3340_story.html) after the grand jury decision was announced, representing the 4.5 hours that Brown's body was left on the street after he was shot in Ferguson, Missouri.

The next month, protesters in New York held an [11 minute silence, symbolizing the eleven times that Eric Garner said "I can't breathe"](https://www.nytimes.com/2014/12/05/nyregion/protests-continue-after-grand-jury-decision-in-eric-garner-case.html).

In 2017, protesters in St. Louis, Missouri, held a [six minute silence, representing the six years](https://www.scpr.org/news/2017/09/17/75724/st-louis-protesters-tell-police-stop-killing-us/) between the death of Anthony Lamar Smith and the acquittal of the white police officer who shot him.

But perhaps the closest antecedent of the 8:46 minute silences for George Floyd comes from a different cause altogether: the silence led by Emma Gonzalez at the *March for Our Lives* in 2018, bringing her time on the podium up to 6 minutes and 20 seconds, the time it took for the gunman to kill 17 students at Marjory Stoneman Douglas High School.

``` {r, fig.align="center"} 
blogdown::shortcode("tweet", "977620153847435264")
```

What this example illustrates is both continuity of protest repertoires -- familiar scripts with innovation at the margins -- but also their *modularity*, their capacity to be borrowed and transplanted from one context to another.

The concept of *modularity*, first introduced by @tarrow1993modular, was a way of delineating the "modern" protest repertoires that emerged in the nineteenth century from their "traditional" predecessors.

Traditional protest repertoires were marked by a particular kind of *directness*. Food prices too high? Time for a grain seizure! Rich dude getting handsy with his servants? Sack his house! Another weaver undercutting your wages? Cut the silk from his loom!

These protest repertoires were well-established but highly segmented. Grievances were typically construed within a single community and redress was targeted directly at the offenders or the local authorities. 

But in "modern" protest repertoire, the focus shifted from the local to the national. Grievances were construed on a much wider scale, and redress was typically targeted at national parliaments. 

Losing the direct link between action and reaction allowed these types of protests to become fully modular -- disconnected from the identity of a particular group or particular grievance. Tarrow describes several modular protest repertoires -- the strike, the boycott, the barricade -- but perhaps the best example is the petition to Parliament combined with a mass march/demonstration on the streets. 

By 1848, a year of dramatic political upheaval in Europe, these new modular forms of contention had become familiar. And, of course, it is striking that a century-and-a-half later, the repertoire of the combined public march and demonstration is still one of the foremost tools in the protester's toolkit, in Europe and beyond.

Indeed, even in the midst of a global pandemic which made large public gatherings extremely risky, this was still the default response of protesters around the world to the death of George Floyd.

This isn't just down to a lack of imagination or creativity. Common repertoires play an important role in helping protesters to mobilize more or less spontaneously. It mitigates both the coordination problem: we might all have different ideas about how to protest in a particular situation, but we know that the effectiveness of our protest is tied to our ability to act in unison.

Now one way to think about the 8:46 silences is to trace the history these public actions from top-down commemorative events to -- I would argue -- a modern, modular, protest repertoire.

## Origins of "silence"

One obvious derivation for the practice of holding a moment's silence is the [Two Minute Silence](https://en.wikipedia.org/wiki/Two-minute_silence) observed in the U.K. and elsewhere at 11am on 11 November to commemorate those who lost their lives in the First World War.

The practice of holding a commemorative silence was already established in Britain prior to WWI: a minute's silence was held for the death of King Edward VII in 1910 and the sinking of the Titanic in 1912. But the origins of the Armistice Day silence are often traced to Cape Town, South Africa, where the "two minute's pause" was held *daily* towards the end of WWI.

- minute's silence at football games - silent inflation
- contested whether silence or applause is most appropriate

not clear when the technique of public silences crossed from the commemorative (though still of course political) to the *contentious*.

But it has been used by just about every one of the new social movements that took off in the 1970s.

anti-nuclear campaigners 

## Why silence?

- silence = speaking out without speaking. quote from 1917 pamphlet. draws you in. 

- silence = intensity of emotion. serves an important legitimizing function that was clearly recognized in Britain. (but also, see the EU's 3 minute silence for the madrid bombings)

- silences can be broken even by one person = hence a display of collective strength
- Weimar Germany example; Man U example

- silence is both a kind of freedom and constraint. constraint = discipline, Victorian era sober sensibilities. it is thus a "training device". but freedom in that individuals can think what they like! quote Daily Herald. quote Tommie Smith. nothing specific to oppose about it.

- silence has a certain respectability or dignity due to its association with rituals of grief. 1917 Silent Parade. quote Tommie Smith (hoo raa). parts of the women's movement that used silence to highlight that their voices, when used, were ignored. notably the new emotional movements often used silence, as well as the conspicuous absence of signs, slogans, banners, or even demands. 

## Silent technologies

The practice was brought to the U.K. by the recommendation of Sir Percy Fitzpatrick -- a South African politician whose eldest son was killed in action in France in 1917.

King George V was enthusiastic about the idea and a statement was carried in The Times announcing it just a few days before on 7 November 1919. The King perhaps underestimated the difficulty of transplanting a practice from one city to an entire nation, with a rather casual insistence that "no elaborate organisation appears to be necessary" [@gregory2014silence].

In fact, there were obvious logistical difficulties. Since most would have to observe the silence in their place of work rather than congregating in a public space, an audible signal would be necessary to coordinate the silence. But in 1919, Britain still lacked a fully centralized and precise system of time-keeping. @lichau2019soundproof describes the logistical challenge:

> The allegedly homogeneous sound of silence was not simply achieved by collectively listening. This sound also had to be produced: the population had to fall silent at precisely the same moment, throughout the whole country, at 11h, 0 min, 0 sec.
> While synchronization with the colonies and dominions was impossible due to the enormous time differences, it also turned out to be a quite difficult and problematic task even in the British homeland, particularly in big cities and metropoles. During the 1920s, maroons were the acoustic devices most commonly used for signalling the beginning of the silence within the confines of the different districts and neighbourhoods. These maroons had to be synchronized if the silence was to take place at the same time everywhere. Yet, in the early years of the minute’s silence, London’s system of locally installed clocks connected to centrally adjusted devices of time measurement was not yet sufficiently built up. Thus, while the silence had already begun in one town district, maroons or gun fire from neighbouring districts repeatedly disturbed the silence that was supposed to articulate a 'perfect' unity. [@lichau2019soundproof, pp.852-2]

- maroons in england
- importance of the radio
- see tech examples of 8:46 - spotify, radio, tv, etc.
- the video recording itself lends a concreteness to the 8:46. while that number turns out to have been an error, the belieavability - or unbelievability of the magnitude comes from the existence of the video.

while the Armistice Day silence was a kind of reenactment -- the silence as the gunfire stopped at 11am -- the silences for George Floyd have an even more direct sense of recollection. quotes from organizers about how kneeling or lying down for that long brought home the reality of what happened. 









## Political silences

Lots of silences are political. But only a subset of those are also *contentious* -- challenging the status quo.

Many forms of silence actually *uphold* the status quo -- whether its governments denying genocides, or Hollywood insiders keeping Harvey Weinstein's "open secret". Silen*cing*, too, is often a way of upholding the status quo through repression or censorship.

Silence can also be a tool of *resistance* -- it is a classic "weapon of the weak" as James Scott put it in his study of the anonymous tactics of peasant resistance [@scott2008weapons]. To take a more proximate example: organizations like [*Flex Your Rights*](https://www.flexyourrights.org/faqs/when-can-police-ask-for-id/) in the U.S. encourage citizens to exercise their constitutional rights in interactions with the police, such as by refusing to identify yourself when you are not legally required to.

But while acts of resistance challenge the status quo *directly*, contentious politics is typically about challenging the status quo more broadly, by advancing claims that bear on the interests of others.







