---
title: Hokus focus (group)
author: Sophie Hill
date: '2020-01-19'
slug: focus-group
categories:
  - Methods
tags:
  - Campaigns
  - Public opinion
draft: yes
description: What can we learn from focus groups?
---

Arguments in favour of the usefulness of focus groups:

1. They tell us things that pollsters might miss

I've always been puzzled by this argument. Most standard political surveys include at least one question that is either open-ended or allows for a very wide range of responses - typically a question about the "most important issue" facing the country.
In general, I'd be more persuaded if proponents of this argument could actually point to an example of an insight gleaned from a focus group that wasn't evident from existing surveys.

2. They tell us things that couldn't be conveyed via a survey, even if pollsters knew what to ask

Presumably this is because focus groups like to ask people things like: what does politician X like to do on a saturday night? 
There is really no evidence to think these responses have any informative value beyond (i) well-known stereotypes of politicians as portrayed in the media; (ii) basic perceptions of competence/warmth, in line with the social psychology model of social cognition.

Or: perhaps they tell us something about the intensity of opinion? e.g. how enthused the voters are? Maybe, but again we have a lot of survey questions for this.

3. It's better to see how voters think and discuss politics in a group, since that's closer to how it is in real life.

It's true that politics is a social process. But just putting people in a group of 6-8 strangers does not automatically increase external validity! For one thing, most people only discuss politics with close friends, family, and coworkers, who are likely homogeneous on many dimension - whereas focus groups are, usually by construction, hetereogeneous. Secondly, discussing politics with your mates in the pub is probably quite different from being paid to particiate in a focus group when you know that your responses are being recorded.

It's good for us to approximate real-world conditions. But to do that, we need to think carefully about what those conditions are, and then we need to explicitly model them in a reduced form setting!

I think it's time to be honest: focus groups are not really about understanding voters. At least not the way that most UK based pollsters and analysts use them. Focus groups are about producing amusing soundbites that can then be quoted in a follow up piece.





"I've voted Labour all my life, but won't vote for Corbyn"

@himmelweit1978memory show that voters are not very accurate in recalling their vote at past elections



### Proofiness

Let's start with a more basic question: if we wanted to show that campaign slogans affect election results, what kind of evidence would we need?

One answer - suggested by [many](https://www.theguardian.com/politics/2019/dec/06/johnsons-get-brexit-done-strategy-resonates-with-marginal-focus-groups) [commentators](https://www.ft.com/content/c75273fe-183d-11ea-8d73-6303645ac406) - is to ask voters why they are voting the way they are. And, lo and behold, many participants in these focus groups explicitly said they were voting Conservative _in order to Get Brexit Done_. 

A smoking gun, surely? Straight from the voter's mouth!

Perhaps not. These anecdotes are closer to _proofiness_ that, erm, proof.^[Inspired by Stephen Colbert's "[truthiness](https://www.merriam-webster.com/words-at-play/truthiness-meaning-word-origin)", the quality of seeming to be true but not necessarily or actually true according to known facts.]

Voters are not the best guides to what is in their heads.

They underestimate how much their beliefs are affected by others in a group discussion, even misremembering their initial attitudes [@keating2016partisan]

voters do not actually place more weight on the issue they say is "most important" [@bartle2012telling]

@theodoridis2017me voters don't just have implicit attitudes, they also have implicit _identities_. it has been well-known, for example, that many of those who identify as independents who, say, lean towards the Democratic party in the US, look much more like Democrats than pure Independents... this paper demostrates this with an implicit association test that forms a much better scale of partisan attachment!
